import csv
import os
from datetime import datetime
from decimal import Decimal

# Data extracted from SQL INSERT statements
categories_data = [
    {'name': 'National Park', 'description': '', 'icon': ''},
    {'name': 'Lake', 'description': '', 'icon': ''},
    {'name': 'Museum', 'description': '', 'icon': ''},
    {'name': 'Historical Site', 'description': '', 'icon': ''},
    {'name': 'Viewpoint', 'description': '', 'icon': ''},
    {'name': 'Waterfall', 'description': '', 'icon': ''},
    {'name': 'Geothermal Site', 'description': '', 'icon': ''},
    {'name': 'Wildlife Conservancy', 'description': '', 'icon': ''},
    {'name': 'Nature Reserve', 'description': '', 'icon': ''},
    {'name': 'Prehistoric Site', 'description': '', 'icon': ''},
]

attraction_sites_data = [
    {
        'name': 'Lake Nakuru National Park',
        'description': 'Famed for its flamingos, rhinos, and diverse wildlife.',
        'category': 'National Park',
        'latitude': '-0.40325924',
        'longitude': '36.09613496',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Menengai Crater',
        'description': 'One of the largest volcanic craters globally, offering panoramic views.',
        'category': 'Viewpoint',
        'latitude': '-0.223433814',
        'longitude': '36.09549526',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Hyrax Hill Prehistoric Site',
        'description': 'An archaeological site showcasing early human settlements.',
        'category': 'Museum',
        'latitude': '-0.28123318',
        'longitude': '36.10473476',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Lord Egerton Castle',
        'description': 'A historic castle with unique architecture and history.',
        'category': 'Museum',
        'latitude': '-0.274638726',
        'longitude': '35.97213372',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Lake Naivasha',
        'description': 'A freshwater lake popular for boat rides and bird watching.',
        'category': 'Lake',
        'latitude': '-0.745886825',
        'longitude': '36.3223929',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Hell\'s Gate National Park',
        'description': 'Hell\'s Gate National Park',
        'category': 'National Park',
        'latitude': '-0.716941784',
        'longitude': '36.43105192',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Crescent Island Game Sanctuary',
        'description': 'A private sanctuary offering walking safaris.',
        'category': 'Wildlife Conservancy',
        'latitude': '-0.773989859',
        'longitude': '36.40395939',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Mount Longonot National Park',
        'description': 'A dormant volcano offering hiking opportunities.',
        'category': 'National Park',
        'latitude': '-0.9158',
        'longitude': '36.44628702',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Lake Elementaita',
        'description': 'A UNESCO World Heritage Site, ideal for bird watching.',
        'category': 'Lake',
        'latitude': '-0.441103369',
        'longitude': '36.24176334',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Olkaria Geothermal Spa',
        'description': 'Hot spa pools amidst geothermal activity.',
        'category': 'Geothermal Site',
        'latitude': '-0.860900903',
        'longitude': '36.29482167',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Kariandusi Prehistoric Site',
        'description': 'An important archaeological site with ancient tools.',
        'category': 'Prehistoric Site',
        'latitude': '-0.451510002',
        'longitude': '36.2845125',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Crater Lake Game Sanctuary',
        'description': 'A scenic sanctuary with a volcanic crater lake.',
        'category': 'Wildlife Conservancy',
        'latitude': '-0.773146847',
        'longitude': '36.25820055',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Makalia Waterfalls',
        'description': 'A picturesque waterfall within Lake Nakuru National Park.',
        'category': 'Nature Reserve',
        'latitude': '-0.491895737',
        'longitude': '36.08090849',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Ol Doinyo Eburru',
        'description': 'A volcanic mountain offering hiking trails and geothermal features.',
        'category': 'Viewpoint',
        'latitude': '-0.647429872',
        'longitude': '36.18995087',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Lake Oloiden',
        'description': 'A serene lake known for its hot springs and birdlife.',
        'category': 'Lake',
        'latitude': '-0.812671847',
        'longitude': '36.2791271',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Hippo Point Wildlife Conservancy',
        'description': 'A conservation area ideal for wildlife viewing.',
        'category': 'Wildlife Conservancy',
        'latitude': '-0.799490121',
        'longitude': '36.30676597',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Elsamere Nature Reserve',
        'description': 'Former home of Joy Adamson, now a conservation center.',
        'category': 'Nature Reserve',
        'latitude': '-0.820899494',
        'longitude': '36.31049039',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Kigio Wildlife Conservancy',
        'description': 'A community-owned conservancy supporting eco-tourism.',
        'category': 'Wildlife Conservancy',
        'latitude': '-0.567112179',
        'longitude': '36.39407167',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Oserengoni Wildlife Sanctuary',
        'description': 'A private sanctuary focusing on conservation and tourism.',
        'category': 'Wildlife Conservancy',
        'latitude': '-0.830670307',
        'longitude': '36.24700324',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Dodo\'s Tower',
        'description': 'A unique structure offering panoramic views of the surrounding area.',
        'category': 'Wildlife Conservancy',
        'latitude': '-0.804920261',
        'longitude': '36.29048252',
        'address': '',
        'opening_hours': '9:00 AM - 5:00 PM',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'image': '',
        'is_active': 'True',
    },
]

# Updated pricing data with all visitor types from the Pricing model
pricing_data = [
    # Lake Nakuru National Park
    {'attraction_site': 'Lake Nakuru National Park', 'visitor_type': 'adult', 'price': '1000', 'currency': 'KES'},
    {'attraction_site': 'Lake Nakuru National Park', 'visitor_type': 'child', 'price': '1000', 'currency': 'KES'},
    {'attraction_site': 'Lake Nakuru National Park', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Lake Nakuru National Park', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Hell's Gate National Park
    {'attraction_site': 'Hell\'s Gate National Park', 'visitor_type': 'adult', 'price': '800', 'currency': 'KES'},
    {'attraction_site': 'Hell\'s Gate National Park', 'visitor_type': 'child', 'price': '800', 'currency': 'KES'},
    {'attraction_site': 'Hell\'s Gate National Park', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Hell\'s Gate National Park', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Lake Naivasha
    {'attraction_site': 'Lake Naivasha', 'visitor_type': 'adult', 'price': '500', 'currency': 'KES'},
    {'attraction_site': 'Lake Naivasha', 'visitor_type': 'child', 'price': '500', 'currency': 'KES'},
    {'attraction_site': 'Lake Naivasha', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Lake Naivasha', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Menengai Crater
    {'attraction_site': 'Menengai Crater', 'visitor_type': 'adult', 'price': '100', 'currency': 'KES'},
    {'attraction_site': 'Menengai Crater', 'visitor_type': 'child', 'price': '100', 'currency': 'KES'},
    {'attraction_site': 'Menengai Crater', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Menengai Crater', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Lord Egerton Castle
    {'attraction_site': 'Lord Egerton Castle', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Lord Egerton Castle', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Lord Egerton Castle', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Lord Egerton Castle', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Mount Longonot National Park
    {'attraction_site': 'Mount Longonot National Park', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Mount Longonot National Park', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Mount Longonot National Park', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Mount Longonot National Park', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Olkaria Geothermal Spa
    {'attraction_site': 'Olkaria Geothermal Spa', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Olkaria Geothermal Spa', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Olkaria Geothermal Spa', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Olkaria Geothermal Spa', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Kariandusi Prehistoric Site
    {'attraction_site': 'Kariandusi Prehistoric Site', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Kariandusi Prehistoric Site', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Kariandusi Prehistoric Site', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Kariandusi Prehistoric Site', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Lake Elementaita
    {'attraction_site': 'Lake Elementaita', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Lake Elementaita', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Lake Elementaita', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Lake Elementaita', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Crescent Island Game Sanctuary
    {'attraction_site': 'Crescent Island Game Sanctuary', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Crescent Island Game Sanctuary', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Crescent Island Game Sanctuary', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Crescent Island Game Sanctuary', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Crater Lake Game Sanctuary
    {'attraction_site': 'Crater Lake Game Sanctuary', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Crater Lake Game Sanctuary', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Crater Lake Game Sanctuary', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Crater Lake Game Sanctuary', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Makalia Waterfalls
    {'attraction_site': 'Makalia Waterfalls', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Makalia Waterfalls', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Makalia Waterfalls', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Makalia Waterfalls', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Ol Doinyo Eburru
    {'attraction_site': 'Ol Doinyo Eburru', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Ol Doinyo Eburru', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Ol Doinyo Eburru', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Ol Doinyo Eburru', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Lake Oloiden
    {'attraction_site': 'Lake Oloiden', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Lake Oloiden', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Lake Oloiden', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Lake Oloiden', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Hippo Point Wildlife Conservancy
    {'attraction_site': 'Hippo Point Wildlife Conservancy', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Hippo Point Wildlife Conservancy', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Hippo Point Wildlife Conservancy', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Hippo Point Wildlife Conservancy', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Elsamere Nature Reserve
    {'attraction_site': 'Elsamere Nature Reserve', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Elsamere Nature Reserve', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Elsamere Nature Reserve', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Elsamere Nature Reserve', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Kigio Wildlife Conservancy
    {'attraction_site': 'Kigio Wildlife Conservancy', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Kigio Wildlife Conservancy', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Kigio Wildlife Conservancy', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Kigio Wildlife Conservancy', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Oserengoni Wildlife Sanctuary
    {'attraction_site': 'Oserengoni Wildlife Sanctuary', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Oserengoni Wildlife Sanctuary', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Oserengoni Wildlife Sanctuary', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Oserengoni Wildlife Sanctuary', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Dodo's Tower
    {'attraction_site': 'Dodo\'s Tower', 'visitor_type': 'adult', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Dodo\'s Tower', 'visitor_type': 'child', 'price': '0.00', 'currency': 'KES'},
    {'attraction_site': 'Dodo\'s Tower', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Dodo\'s Tower', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
    
    # Hyrax Hill Prehistoric Site
    {'attraction_site': 'Hyrax Hill Prehistoric Site', 'visitor_type': 'adult', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Hyrax Hill Prehistoric Site', 'visitor_type': 'child', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Hyrax Hill Prehistoric Site', 'visitor_type': 'student', 'price': '', 'currency': 'KES'},
    {'attraction_site': 'Hyrax Hill Prehistoric Site', 'visitor_type': 'family', 'price': '', 'currency': 'KES'},
]

visitor_stats_data = [
    {'attraction_site': 'Lake Nakuru National Park', 'year': '2020', 'visitor_count': '50000'},
    {'attraction_site': 'Lake Nakuru National Park', 'year': '2021', 'visitor_count': '75000'},
    {'attraction_site': 'Lake Nakuru National Park', 'year': '2022', 'visitor_count': '150000'},
    {'attraction_site': 'Lake Nakuru National Park', 'year': '2023', 'visitor_count': '200000'},
    {'attraction_site': 'Menengai Crater', 'year': '2020', 'visitor_count': '12000'},
    {'attraction_site': 'Menengai Crater', 'year': '2021', 'visitor_count': '18000'},
    {'attraction_site': 'Menengai Crater', 'year': '2022', 'visitor_count': '35000'},
    {'attraction_site': 'Menengai Crater', 'year': '2023', 'visitor_count': '50000'},
    {'attraction_site': 'Hyrax Hill Prehistoric Site', 'year': '2020', 'visitor_count': '2500'},
    {'attraction_site': 'Hyrax Hill Prehistoric Site', 'year': '2021', 'visitor_count': '5000'},
    {'attraction_site': 'Hyrax Hill Prehistoric Site', 'year': '2022', 'visitor_count': '8000'},
    {'attraction_site': 'Hyrax Hill Prehistoric Site', 'year': '2023', 'visitor_count': '10000'},
    {'attraction_site': 'Lord Egerton Castle', 'year': '2020', 'visitor_count': '3500'},
    {'attraction_site': 'Lord Egerton Castle', 'year': '2021', 'visitor_count': '6000'},
    {'attraction_site': 'Lord Egerton Castle', 'year': '2022', 'visitor_count': '12000'},
    {'attraction_site': 'Lord Egerton Castle', 'year': '2023', 'visitor_count': '15000'},
    {'attraction_site': 'Lake Naivasha', 'year': '2020', 'visitor_count': '60000'},
    {'attraction_site': 'Lake Naivasha', 'year': '2021', 'visitor_count': '100000'},
    {'attraction_site': 'Lake Naivasha', 'year': '2022', 'visitor_count': '200000'},
    {'attraction_site': 'Lake Naivasha', 'year': '2023', 'visitor_count': '300000'},
    {'attraction_site': 'Hell\'s Gate National Park', 'year': '2020', 'visitor_count': '20000'},
    {'attraction_site': 'Hell\'s Gate National Park', 'year': '2021', 'visitor_count': '35000'},
    {'attraction_site': 'Hell\'s Gate National Park', 'year': '2022', 'visitor_count': '60000'},
    {'attraction_site': 'Hell\'s Gate National Park', 'year': '2023', 'visitor_count': '80000'},
    {'attraction_site': 'Mount Longonot National Park', 'year': '2020', 'visitor_count': '10000'},
    {'attraction_site': 'Mount Longonot National Park', 'year': '2021', 'visitor_count': '20000'},
    {'attraction_site': 'Mount Longonot National Park', 'year': '2022', 'visitor_count': '35000'},
    {'attraction_site': 'Mount Longonot National Park', 'year': '2023', 'visitor_count': '40000'},
    {'attraction_site': 'Olkaria Geothermal Spa', 'year': '2020', 'visitor_count': '5000'},
    {'attraction_site': 'Olkaria Geothermal Spa', 'year': '2021', 'visitor_count': '8000'},
    {'attraction_site': 'Olkaria Geothermal Spa', 'year': '2022', 'visitor_count': '15000'},
    {'attraction_site': 'Olkaria Geothermal Spa', 'year': '2023', 'visitor_count': '25000'},
    {'attraction_site': 'Kariandusi Prehistoric Site', 'year': '2020', 'visitor_count': '1000'},
    {'attraction_site': 'Kariandusi Prehistoric Site', 'year': '2021', 'visitor_count': '2500'},
    {'attraction_site': 'Kariandusi Prehistoric Site', 'year': '2022', 'visitor_count': '4000'},
    {'attraction_site': 'Kariandusi Prehistoric Site', 'year': '2023', 'visitor_count': '5000'},
    {'attraction_site': 'Lake Elementaita', 'year': '2020', 'visitor_count': '6000'},
    {'attraction_site': 'Lake Elementaita', 'year': '2021', 'visitor_count': '10000'},
    {'attraction_site': 'Lake Elementaita', 'year': '2022', 'visitor_count': '20000'},
    {'attraction_site': 'Lake Elementaita', 'year': '2023', 'visitor_count': '30000'},
    {'attraction_site': 'Crescent Island Game Sanctuary', 'year': '2020', 'visitor_count': '4000'},
    {'attraction_site': 'Crescent Island Game Sanctuary', 'year': '2021', 'visitor_count': '8000'},
    {'attraction_site': 'Crescent Island Game Sanctuary', 'year': '2022', 'visitor_count': '15000'},
    {'attraction_site': 'Crescent Island Game Sanctuary', 'year': '2023', 'visitor_count': '20000'},
    {'attraction_site': 'Crater Lake Game Sanctuary', 'year': '2020', 'visitor_count': '3500'},
    {'attraction_site': 'Crater Lake Game Sanctuary', 'year': '2021', 'visitor_count': '7000'},
    {'attraction_site': 'Crater Lake Game Sanctuary', 'year': '2022', 'visitor_count': '12000'},
    {'attraction_site': 'Crater Lake Game Sanctuary', 'year': '2023', 'visitor_count': '15000'},
    {'attraction_site': 'Makalia Waterfalls', 'year': '2020', 'visitor_count': '2000'},
    {'attraction_site': 'Makalia Waterfalls', 'year': '2021', 'visitor_count': '4000'},
    {'attraction_site': 'Makalia Waterfalls', 'year': '2022', 'visitor_count': '8000'},
    {'attraction_site': 'Makalia Waterfalls', 'year': '2023', 'visitor_count': '10000'},
    {'attraction_site': 'Ol Doinyo Eburru', 'year': '2020', 'visitor_count': '2500'},
    {'attraction_site': 'Ol Doinyo Eburru', 'year': '2021', 'visitor_count': '5000'},
    {'attraction_site': 'Ol Doinyo Eburru', 'year': '2022', 'visitor_count': '10000'},
    {'attraction_site': 'Ol Doinyo Eburru', 'year': '2023', 'visitor_count': '12000'},
    {'attraction_site': 'Lake Oloiden', 'year': '2020', 'visitor_count': '3000'},
    {'attraction_site': 'Lake Oloiden', 'year': '2021', 'visitor_count': '6000'},
    {'attraction_site': 'Lake Oloiden', 'year': '2022', 'visitor_count': '12000'},
    {'attraction_site': 'Lake Oloiden', 'year': '2023', 'visitor_count': '15000'},
    {'attraction_site': 'Hippo Point Wildlife Conservancy', 'year': '2020', 'visitor_count': '4000'},
    {'attraction_site': 'Hippo Point Wildlife Conservancy', 'year': '2021', 'visitor_count': '7000'},
    {'attraction_site': 'Hippo Point Wildlife Conservancy', 'year': '2022', 'visitor_count': '13000'},
    {'attraction_site': 'Hippo Point Wildlife Conservancy', 'year': '2023', 'visitor_count': '15000'},
    {'attraction_site': 'Elsamere Nature Reserve', 'year': '2020', 'visitor_count': '4000'},
    {'attraction_site': 'Elsamere Nature Reserve', 'year': '2021', 'visitor_count': '3000'},
    {'attraction_site': 'Elsamere Nature Reserve', 'year': '2022', 'visitor_count': '5000'},
    {'attraction_site': 'Elsamere Nature Reserve', 'year': '2023', 'visitor_count': '6000'},
    {'attraction_site': 'Kigio Wildlife Conservancy', 'year': '2020', 'visitor_count': '2000'},
    {'attraction_site': 'Kigio Wildlife Conservancy', 'year': '2021', 'visitor_count': '4000'},
    {'attraction_site': 'Kigio Wildlife Conservancy', 'year': '2022', 'visitor_count': '8000'},
    {'attraction_site': 'Kigio Wildlife Conservancy', 'year': '2023', 'visitor_count': '10000'},
    {'attraction_site': 'Oserengoni Wildlife Sanctuary', 'year': '2020', 'visitor_count': '1500'},
    {'attraction_site': 'Oserengoni Wildlife Sanctuary', 'year': '2021', 'visitor_count': '3000'},
    {'attraction_site': 'Oserengoni Wildlife Sanctuary', 'year': '2022', 'visitor_count': '6000'},
    {'attraction_site': 'Oserengoni Wildlife Sanctuary', 'year': '2023', 'visitor_count': '7000'},
    {'attraction_site': 'Dodo\'s Tower', 'year': '2020', 'visitor_count': '1000'},
    {'attraction_site': 'Dodo\'s Tower', 'year': '2021', 'visitor_count': '2000'},
    {'attraction_site': 'Dodo\'s Tower', 'year': '2022', 'visitor_count': '3000'},
    {'attraction_site': 'Dodo\'s Tower', 'year': '2023', 'visitor_count': '3500'},
]

# Hotel data
hotels_data = [
    {
        'name': 'Sarova Lion Hill Game Lodge',
        'description': 'Luxury lodge inside Lake Nakuru NP.',
        'latitude': '-0.3664',
        'longitude': '36.1044',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 5,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'L.Nakuru Lodge',
        'description': 'Eco-friendly lodge',
        'latitude': '-0.3907',
        'longitude': '36.0966',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 3,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'The Cliff',
        'description': 'Boutique camp on the edge of Lake Nakuru.',
        'latitude': '-0.3551',
        'longitude': '36.0692',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 4,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Mbweha Camp',
        'description': 'Rustic cottages in Congreve Conservancy.',
        'latitude': '-0.4725',
        'longitude': '36.1950',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 3,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Hotel Waterbuck',
        'description': 'Business hotel in Nakuru City.',
        'latitude': '-0.2858',
        'longitude': '36.0684',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 3,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'The Royal City Hotel',
        'description': 'Budget-friendly hotel in Nakuru CBD.',
        'latitude': '-0.2922',
        'longitude': '36.0725',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 2,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'The Panari Resort',
        'description': 'Luxury resort near Thompson Falls, Nyahururu.',
        'latitude': '0.0401',
        'longitude': '36.3712',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 5,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Lake Nakuru Sopa Lodge',
        'description': 'Elevated lodge with views of Lake Nakuru.',
        'latitude': '-0.4497',
        'longitude': '36.1264',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 4,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Lake Naivasha Serena Resort',
        'description': 'Upscale resort on Lake Naivasha shores.',
        'latitude': '-0.8354',
        'longitude': '36.3534',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 5,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Sopa Resort Naivasha',
        'description': 'Lodge where wildlife roams the lawns.',
        'latitude': '-0.8197',
        'longitude': '36.4022',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 4,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Lake Naivasha Resort',
        'description': 'Popular resort on Moi South Lake Road.',
        'latitude': '-0.7966',
        'longitude': '36.4258',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 4,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Crater Lake Camp',
        'description': 'Tented camp near a volcanic crater lake.',
        'latitude': '-0.7854',
        'longitude': '36.2736',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 3,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Pelican Lodge',
        'description': 'Quiet lodge on Lake Elementaita.',
        'latitude': '-0.4468',
        'longitude': '36.2483',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 3,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Lake Elementaita Serena Camp',
        'description': 'Luxury tents in Soysambu Conservancy.',
        'latitude': '-0.4355',
        'longitude': '36.2415',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 5,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Kigio Wildlife Camp',
        'description': 'Eco-lodge in Gilgil/Naivasha area.',
        'latitude': '-0.5675',
        'longitude': '36.3933',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 3,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Oserengoni Lodge',
        'description': 'Exclusive lodge in Oserengoni Sanctuary.',
        'latitude': '-0.8315',
        'longitude': '36.2995',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 4,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
    {
        'name': 'Lake Oloiden Resort',
        'description': 'Serene campsite and lodge near Naivasha.',
        'latitude': '-0.8127',
        'longitude': '36.2791',
        'address': '',
        'contact_phone': '',
        'contact_email': '',
        'website': '',
        'star_rating': 3,
        'price_per_night': '',
        'currency': 'KES',
        'total_rooms': '',
        'available_rooms': '',
        'amenities': '',
        'check_in_time': '14:00',
        'check_out_time': '11:00',
        'image': '',
        'is_active': 'True',
    },
]


def create_csv(filename, fieldnames, data):
   
    os.makedirs('exports', exist_ok=True)
    
    filepath = os.path.join('exports', filename)
    with open(filepath, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(data)
    
    print(f" Created: {filepath}")


def main():
  
    print("Generating CSV files from database models...\n")
    
    # Category CSV
    create_csv(
        'categories.csv',
        ['name', 'description', 'icon', 'created_at', 'updated_at'],
        [
            {**row, 'created_at': '', 'updated_at': ''}
            for row in categories_data
        ]
    )
    
    # AttractionSite CSV
    create_csv(
        'attraction_sites.csv',
        ['name', 'description', 'category', 'latitude', 'longitude', 'address', 
         'opening_hours', 'contact_phone', 'contact_email', 'website', 'image', 
         'is_active', 'created_at', 'updated_at'],
        [
            {**row, 'created_at': '', 'updated_at': ''}
            for row in attraction_sites_data
        ]
    )
    
    # Pricing CSV
    create_csv(
        'pricing.csv',
        ['attraction_site', 'visitor_type', 'price', 'currency', 'valid_from', 
         'valid_until', 'is_active', 'created_at', 'updated_at'],
        [
            {**row, 'valid_from': '', 'valid_until': '', 'is_active': 'True', 
             'created_at': '', 'updated_at': ''}
            for row in pricing_data
        ]
    )
    
    # VisitorStat CSV
    create_csv(
        'visitor_stats.csv',
        ['attraction_site', 'year', 'visitor_count'],
        visitor_stats_data
    )
    
    # Hotel CSV
    create_csv(
        'hotels.csv',
        ['name', 'description', 'latitude', 'longitude', 'address', 'contact_phone',
         'contact_email', 'website', 'star_rating', 'price_per_night', 'currency',
         'total_rooms', 'available_rooms', 'amenities', 'check_in_time', 'check_out_time',
         'image', 'is_active', 'created_at', 'updated_at'],
        [
            {**row, 'created_at': '', 'updated_at': ''}
            for row in hotels_data
        ]
    )
    
    print("\n All CSV files generated successfully in the 'exports' directory!")


if __name__ == '__main__':
    main()
