"""
Django settings for nakuru_tourism_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env()
environ.Env.read_env(BASE_DIR/ '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic', #added
    'django.contrib.staticfiles',

    #3rd party apps 
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken', # manages tokens
    'dj_rest_auth', # auth endpoints (log in/out and password reset/change)
    'drf_spectacular',

    #local apps
    'tour_app.apps.TourAppConfig',
]

REST_FRAMEWORK ={
    "DEFAULT_PERMISSION_CLASSES" : [
        "tour_app.permissions.IsAdminOrReadOnly",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    "DEFAULT_SCHEMA_CLASS" : "drf_spectacular.openapi.AutoSchema",
    }

SPECTACULAR_SETTINGS = {
  "TITLE" : "NAKURU TOURISM API",
  "DESCRIPTION": " AN API SHOWING TOURISM ATTRACTION SITES DATA",
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware", # added
    'corsheaders.middleware.CorsMiddleware', #added
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# cross origin resource sharing
CORS_ALLOWED_ORIGINS = (
    "http://localhost:3000",
    "http://localhost:8000", 
    "http://localhost:8501"
)

# to avoid a website to cchange the local architecture
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:6501',
]
                        
ROOT_URLCONF = 'nakuru_tourism_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nakuru_tourism_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'nakuru_tourism_db',
        'USER': 'postgres',
        'PASSWORD' : '987654321Nara',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "static"] # new
STATIC_ROOT = BASE_DIR / "staticfiles" # new
STATICFILES_STORAGE ="whitenoise.storage.CompressedManifestStaticFilesStorage"

VENV_BASE = Path(os.environ.get('VIRTUAL_ENV', BASE_DIR / 'tour_env'))
if os.name =='nt':

    GDAL_PATH =r"C:\Users\DIGIFIT MEDIA\Documents\tour_env\Lib\site-packages\osgeo"

    os.environ['PATH'] = str(GDAL_PATH)+ os.path.pathsep + os.environ['PATH']

    GDAL_LIBRARY_PATH = r"C:\Users\DIGIFIT MEDIA\Documents\tour_env\Lib\site-packages\osgeo\gdal.dll"
    GEOS_LIBRARY_PATH = r"C:\Users\DIGIFIT MEDIA\Documents\tour_env\Lib\site-packages\osgeo\geos_c.dll"
    