# Generated by Django 6.0.5 on 2026-05-25 08:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttractionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=255)),
                ('opening_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attraction_sites/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attraction_sites', to='tour_app.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('star_rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=3)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('total_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amenities', models.TextField(help_text='Comma-separated list of amenities (WiFi, Gym, Restaurant, etc.)')),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['star_rating', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='tour_app_ho_latitud_c2ecc4_idx'), models.Index(fields=['star_rating'], name='tour_app_ho_star_ra_182b9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child (6-17)'), ('student', 'Student'), ('family', 'Family Package')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attraction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='tour_app.attractionsite')),
            ],
            options={
                'ordering': ['attraction_site', 'visitor_type'],
            },
        ),
        migrations.CreateModel(
            name='VisitorStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('visitor_count', models.PositiveIntegerField()),
                ('attraction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_stats', to='tour_app.attractionsite')),
            ],
        ),
        migrations.AddIndex(
            model_name='attractionsite',
            index=models.Index(fields=['latitude', 'longitude'], name='tour_app_at_latitud_92160f_idx'),
        ),
        migrations.AddIndex(
            model_name='attractionsite',
            index=models.Index(fields=['category'], name='tour_app_at_categor_37c44a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together={('attraction_site', 'visitor_type', 'valid_from')},
        ),
    ]
